version: "3.1"
services:
  db:
    container_name: epitafdb
    image: mariadb
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - TZ=Europe/Paris
    volumes:
      - ./tmp:/var/lib/mysql
